"""Stamp and signature marks for invoices."""

from __future__ import annotations

from .digital_signature import signature_render_context
from .digital_stamp import stamp_render_context
from .models import FirmCompanyInformation, Invoice


INVOICE_MARK_STATUSES = frozenset(
    {
        Invoice.Status.GENERATED,
        Invoice.Status.ISSUED,
        Invoice.Status.PARTIALLY_PAID,
        Invoice.Status.PAID,
    }
)


def _signer_employee(invoice):
    if invoice.approved_by_id:
        return invoice.approved_by
    return invoice.created_by


def _mark_date(invoice) -> str:
    when = invoice.approved_at or invoice.created_at
    if when:
        return when.strftime("%d %b %Y")
    if invoice.issue_date:
        return invoice.issue_date.strftime("%d %b %Y")
    return ""


def _stamp_label(invoice) -> str:
    if invoice.status == Invoice.Status.GENERATED:
        return "Generated by"
    return "Issued by"


def invoice_show_marks(invoice) -> bool:
    return invoice.status in INVOICE_MARK_STATUSES


def invoice_marks_context(invoice, *, firm: FirmCompanyInformation | None = None) -> dict:
    """
    Context for invoice stamp + signature blocks.

    Shown for Generated and Issued (and retained after payment).
    """
    firm = firm or FirmCompanyInformation.get_solo()
    if not invoice_show_marks(invoice):
        return {
            "show_invoice_marks": False,
            "stamp_status": "",
            "stamp_status_key": "",
            "stamp_label": "",
            "stamp_name": "",
            "stamp_date": "",
            "signature_name": "",
            "signature_title": "",
            "signature_date": "",
            "signature_initials": "",
        }

    signer = _signer_employee(invoice)
    signer_name = ""
    if signer is not None:
        signer_name = (
            signer.get_full_name() or getattr(signer, "login_code", "") or ""
        ).strip()

    date_display = _mark_date(invoice)
    stamp_ctx = stamp_render_context(
        firm=firm,
        status=invoice.get_status_display(),
        status_key=invoice.status,
        label=_stamp_label(invoice),
        name=firm.display_name,
        date_display=date_display,
    )
    sig_ctx = signature_render_context(
        firm=firm,
        name=signer_name or firm.display_name,
        date_display=date_display,
    )
    return {
        "show_invoice_marks": True,
        **stamp_ctx,
        **sig_ctx,
    }
