# Generated by Django 6.0.7 on 2026-07-18 09:49

import accounts.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('login_code', models.CharField(help_text='6-digit code used to sign in.', max_length=6, unique=True, validators=[django.core.validators.RegexValidator(message='Login code must be exactly 6 digits.', regex='^\\d{6}$')])),
                ('personal_email', models.EmailField(max_length=254, unique=True)),
                ('work_email', models.EmailField(blank=True, help_text='Coming soon — auto-generated from personal email.', max_length=254, null=True)),
                ('personal_phone', models.CharField(max_length=20)),
                ('work_phone', models.CharField(blank=True, help_text='Coming soon — linked work phone number.', max_length=20, null=True)),
                ('id_type', models.CharField(choices=[('citizen', 'Citizen'), ('non_citizen', 'Non-Citizen')], max_length=20)),
                ('identification_number', models.CharField(blank=True, help_text='National ID for citizens.', max_length=50)),
                ('alien_number', models.CharField(blank=True, help_text='Alien / permit number for non-citizens.', max_length=50)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('role', models.CharField(choices=[('firm_admin', 'Firm Administrator'), ('managing_partner', 'Managing Partner'), ('advocate', 'Advocate'), ('intern', 'Intern'), ('it_support', 'IT Support'), ('employee', 'Employee')], default='employee', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['first_name', 'last_name'],
            },
            managers=[
                ('objects', accounts.models.EmployeeManager()),
            ],
        ),
    ]
