# Generated by Django 6.0.7 on 2026-07-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='personal_phone',
            field=models.CharField(max_length=32),
        ),
    ]
