# Generated by Django 6.0.7 on 2026-07-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phone_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='id_country',
            field=models.CharField(default='KE', help_text='Country of nationality / ID issuance. Defaults to Kenya.', max_length=2),
        ),
    ]
