# Generated by Django 5.0.14 on 2026-07-18 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_role_status_enums'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='courtesy_title',
            field=models.CharField(blank=True, choices=[('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.'), ('Miss', 'Miss'), ('Dr', 'Dr.'), ('Prof', 'Prof.'), ('Hon', 'Hon.'), ('Adv', 'Adv.'), ('Rev', 'Rev.'), ('Eng', 'Eng.')], default='', help_text="Courtesy title shown with the employee's name.", max_length=10),
        ),
    ]
