# Generated by Django 5.0.14 on 2026-07-18 11:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_courtesy_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('password', models.CharField(blank=True, default='', max_length=128)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='clients/profiles/')),
                ('google_sub', models.CharField(blank=True, db_index=True, default='', help_text='Google account subject ID when signed up via Google.', max_length=255)),
                ('status', models.CharField(choices=[('pending_onboarding', 'Pending Onboarding'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending_onboarding', max_length=32)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
