# Generated by Django 5.0.14 on 2026-07-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_client_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['company_name', 'first_name', 'last_name'], 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AddField(
            model_name='client',
            name='alien_document',
            field=models.FileField(blank=True, null=True, upload_to='clients/docs/alien/'),
        ),
        migrations.AddField(
            model_name='client',
            name='alien_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='client_type',
            field=models.CharField(choices=[('individual', 'Individual client'), ('corporate', 'Corporate client')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='company_registration_document',
            field=models.FileField(blank=True, null=True, upload_to='clients/docs/company/'),
        ),
        migrations.AddField(
            model_name='client',
            name='company_registration_number',
            field=models.CharField(blank=True, default='', help_text='Business / company registration number.', max_length=80),
        ),
        migrations.AddField(
            model_name='client',
            name='id_type',
            field=models.CharField(blank=True, choices=[('citizen', 'Citizen'), ('non_citizen', 'Non-Citizen')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='client',
            name='identification_document',
            field=models.FileField(blank=True, null=True, upload_to='clients/docs/id/'),
        ),
        migrations.AddField(
            model_name='client',
            name='identification_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='client',
            name='physical_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('pending_onboarding', 'Pending Onboarding'), ('pending_approval', 'Pending Approval'), ('active', 'Active'), ('suspended', 'Suspended')], default='pending_onboarding', max_length=32),
        ),
    ]
