# Generated by Django 5.0.14 on 2026-07-18 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_client_onboarding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='business_document',
            field=models.FileField(blank=True, null=True, upload_to='clients/docs/business/'),
        ),
        migrations.AddField(
            model_name='client',
            name='business_number',
            field=models.CharField(blank=True, default='', help_text='Business registration number.', max_length=80),
        ),
        migrations.AddField(
            model_name='client',
            name='corporate_kind',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('company', 'Company')], default='', help_text='For corporate clients: business or company.', max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_registration_number',
            field=models.CharField(blank=True, default='', help_text='Company registration number.', max_length=80),
        ),
    ]
