# Generated by Django 5.0.14 on 2026-07-18 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_employee_pending_approval_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LitigationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filing_date', models.DateField()),
                ('court_rank', models.CharField(choices=[('supreme_court', 'Supreme Court'), ('court_of_appeal', 'Court of Appeal'), ('high_court', 'High Court'), ('elrc', 'Employment and Labour Relations Court'), ('elc', 'Environment and Land Court'), ('magistrates', "Magistrates' Court"), ('kadhis', "Kadhis' Court"), ('small_claims', 'Small Claims Court'), ('court_martial', 'Court Martial'), ('tribunal', 'Tribunal')], max_length=32)),
                ('case_category', models.CharField(choices=[('civil', 'Civil'), ('criminal', 'Criminal'), ('commercial', 'Commercial'), ('family', 'Family'), ('constitutional', 'Constitutional & Human Rights'), ('judicial_review', 'Judicial Review'), ('employment', 'Employment & Labour'), ('environment', 'Environment & Land'), ('succession', 'Succession'), ('anti_corruption', 'Anti-Corruption'), ('admiralty', 'Admiralty'), ('other', 'Other')], max_length=32)),
                ('case_type', models.CharField(choices=[('suit', 'Suit'), ('petition', 'Petition'), ('application', 'Application'), ('appeal', 'Appeal'), ('revision', 'Revision'), ('judicial_review', 'Judicial Review'), ('originating_summons', 'Originating Summons'), ('miscellaneous', 'Miscellaneous'), ('charge', 'Charge / Criminal Case'), ('other', 'Other')], max_length=32)),
                ('court_case_number', models.CharField(blank=True, default='', max_length=120)),
                ('station', models.CharField(choices=[('nairobi', 'Nairobi'), ('milimani', 'Milimani'), ('mombasa', 'Mombasa'), ('kisumu', 'Kisumu'), ('nakuru', 'Nakuru'), ('eldoret', 'Eldoret'), ('nyeri', 'Nyeri'), ('meru', 'Meru'), ('kakamega', 'Kakamega'), ('kisii', 'Kisii'), ('malindi', 'Malindi'), ('garissa', 'Garissa'), ('machakos', 'Machakos'), ('kitale', 'Kitale'), ('kericho', 'Kericho'), ('embu', 'Embu'), ('bungoma', 'Bungoma'), ('thika', 'Thika'), ('kiambu', 'Kiambu'), ('other', 'Other')], max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending_approval', 'Pending approval'), ('active', 'Active'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending_approval', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='litigation_cases', to='accounts.client')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Litigation case',
                'verbose_name_plural': 'Litigation cases',
                'ordering': ['-filing_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaseParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('party_type', models.CharField(choices=[('plaintiff', 'Plaintiff'), ('defendant', 'Defendant'), ('applicant', 'Applicant'), ('respondent', 'Respondent'), ('petitioner', 'Petitioner'), ('appellant', 'Appellant'), ('accused', 'Accused'), ('interested_party', 'Interested Party'), ('third_party', 'Third Party'), ('other', 'Other')], max_length=32)),
                ('category', models.CharField(blank=True, choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('government', 'Government'), ('other', 'Other')], default='', max_length=32)),
                ('firm_agent', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_client_party', models.BooleanField(default=False, help_text='True when this party row was seeded from the selected client.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='accounts.litigationcase')),
            ],
            options={
                'verbose_name': 'Case party',
                'verbose_name_plural': 'Case parties',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
