# Generated by Django 5.0.14 on 2026-07-18 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_litigation_case_and_parties'),
    ]

    operations = [
        migrations.AddField(
            model_name='litigationcase',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='litigationcase',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='litigationcase',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Employee allocated when the case is approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='litigationcase',
            name='court_rank',
            field=models.CharField(choices=[('supreme_court', 'Supreme Court'), ('court_of_appeal', 'Court of Appeal'), ('high_court', 'High Court'), ('elc', 'Environment and Land Court'), ('elrc', 'Employment and Labour Relations Court'), ('magistrates', "Magistrates' Courts"), ('kadhis', "Kadhi's Courts"), ('court_martial', 'Courts Martial'), ('small_claims', 'Small Claims Court'), ('tribunal', 'Tribunals')], max_length=32),
        ),
        migrations.CreateModel(
            name='CaseTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, default='', help_text='Instructions / brief for the assigned employee.')),
                ('due_date', models.DateField()),
                ('reminder_at', models.DateTimeField(blank=True, help_text='Optional reminder date and time.', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_tasks', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.litigationcase')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_case_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case task',
                'verbose_name_plural': 'Case tasks',
                'ordering': ['due_date', '-created_at'],
            },
        ),
    ]
