# Generated by Django 5.0.14 on 2026-07-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_case_assignment_and_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='litigationcase',
            name='case_category',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='litigationcase',
            name='case_type',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='litigationcase',
            name='court_rank',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='litigationcase',
            name='station',
            field=models.CharField(max_length=120),
        ),
    ]
