# Generated by Django 5.0.14 on 2026-07-18 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_free_text_case_lookups'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonLitigationMatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_opened', models.DateField()),
                ('matter_category', models.CharField(max_length=120)),
                ('matter_title', models.CharField(max_length=255)),
                ('client_instructions', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('pending_approval', 'Pending approval'), ('active', 'Active'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='pending_approval', max_length=32)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_matters', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_matters', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='non_litigation_matters', to='accounts.client')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_matters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Non-litigation matter',
                'verbose_name_plural': 'Non-litigation matters',
                'ordering': ['-date_opened', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatterTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions', models.TextField(blank=True, default='')),
                ('due_date', models.DateField()),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matter_tasks', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_matter_tasks', to=settings.AUTH_USER_MODEL)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='accounts.nonlitigationmatter')),
            ],
            options={
                'verbose_name': 'Matter task',
                'verbose_name_plural': 'Matter tasks',
                'ordering': ['due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatterParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=255)),
                ('party_type', models.CharField(choices=[('client', 'Client'), ('counterparty', 'Counterparty'), ('beneficiary', 'Beneficiary'), ('witness', 'Witness'), ('instructing_party', 'Instructing Party'), ('other', 'Other')], max_length=32)),
                ('category', models.CharField(blank=True, choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('government', 'Government'), ('other', 'Other')], default='', max_length=32)),
                ('firm_agent', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('is_client_party', models.BooleanField(default=False)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='accounts.nonlitigationmatter')),
            ],
            options={
                'verbose_name': 'Matter party',
                'verbose_name_plural': 'Matter parties',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
