# Generated by Django 5.0.14 on 2026-07-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_non_litigation_matters'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ui_font',
            field=models.CharField(blank=True, choices=[('plex', 'IBM Plex + Baskerville'), ('source', 'Source Sans + Source Serif'), ('manrope', 'Manrope + Lora'), ('figtree', 'Figtree + Instrument Serif')], default='plex', help_text="Font pairing for this user's workspace pages.", max_length=32),
        ),
        migrations.AddField(
            model_name='employee',
            name='ui_theme',
            field=models.CharField(blank=True, choices=[('default', 'Role default'), ('firm_admin', 'Firm'), ('managing_partner', 'Partner'), ('advocate', 'Advocate'), ('intern', 'Intern'), ('it_support', 'IT Support'), ('employee', 'Employee')], default='default', help_text="Color theme for this user's workspace pages.", max_length=32),
        ),
    ]
