# Generated by Django 5.0.14 on 2026-07-18 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='ui_density',
            field=models.CharField(blank=True, choices=[('comfortable', 'Comfortable'), ('compact', 'Compact'), ('airy', 'Airy')], default='comfortable', help_text="Spacing density for this user's workspace pages.", max_length=16),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ui_font',
            field=models.CharField(blank=True, choices=[('plex', 'Plex Chambers'), ('source', 'Source Editorial'), ('manrope', 'Manrope Editorial'), ('figtree', 'Figtree Display'), ('sora', 'Sora Brief'), ('outfit', 'Outfit Literata'), ('jakarta', 'Jakarta Crimson'), ('syne', 'Syne Vollkorn'), ('epilogue', 'Epilogue Newsreader'), ('public', 'Public News')], default='plex', help_text="Font pairing for this user's workspace pages.", max_length=32),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ui_theme',
            field=models.CharField(blank=True, choices=[('default', 'Role default'), ('firm_admin', 'Firm violet'), ('managing_partner', 'Partner slate'), ('advocate', 'Advocate green'), ('intern', 'Intern blue'), ('it_support', 'IT graphite'), ('employee', 'Employee rose'), ('midnight', 'Midnight'), ('graphite', 'Graphite'), ('cedar', 'Cedar'), ('cobalt', 'Cobalt'), ('olive', 'Olive'), ('copper', 'Copper'), ('arctic', 'Arctic'), ('espresso', 'Espresso'), ('jade', 'Jade'), ('marine', 'Marine')], default='default', help_text="Color theme for this user's workspace pages.", max_length=32),
        ),
    ]
