# Generated by Django 5.0.14 on 2026-07-18 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_employee_ui_density'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='uniq_notification_recipient_source',
        ),
    ]
