# Generated by Django 5.0.14 on 2026-07-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_notification_drop_conditional_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ui_font',
            field=models.CharField(blank=True, choices=[('plex', 'Plex Chambers'), ('source', 'Source Editorial'), ('manrope', 'Manrope Editorial'), ('figtree', 'Figtree Display'), ('sora', 'Sora Brief'), ('outfit', 'Outfit Literata'), ('jakarta', 'Jakarta Crimson'), ('syne', 'Syne Vollkorn'), ('epilogue', 'Epilogue Newsreader'), ('public', 'Public News'), ('space', 'Space Fraunces'), ('archivo', 'Archivo Playfair'), ('dm', 'DM Pair'), ('urbanist', 'Urbanist Cormorant'), ('bricolage', 'Bricolage Fraunces'), ('lexend', 'Lexend Spectral'), ('work', 'Work Zilla'), ('albert', 'Albert Cardo'), ('redhat', 'Red Hat Stack'), ('cabin', 'Cabin Alegreya')], default='plex', help_text="Font pairing for this user's workspace pages.", max_length=32),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ui_theme',
            field=models.CharField(blank=True, choices=[('default', 'Role default'), ('firm_admin', 'Firm violet'), ('managing_partner', 'Partner slate'), ('advocate', 'Advocate green'), ('intern', 'Intern blue'), ('it_support', 'IT graphite'), ('employee', 'Employee rose'), ('midnight', 'Midnight'), ('graphite', 'Graphite'), ('cedar', 'Cedar'), ('cobalt', 'Cobalt'), ('olive', 'Olive'), ('copper', 'Copper'), ('arctic', 'Arctic'), ('espresso', 'Espresso'), ('jade', 'Jade'), ('marine', 'Marine'), ('sunrise', 'Sunrise'), ('citrus', 'Citrus'), ('azure', 'Azure'), ('emerald', 'Emerald'), ('saffron', 'Saffron'), ('flamingo', 'Flamingo'), ('electric', 'Electric'), ('ruby', 'Ruby'), ('lime', 'Lime'), ('orchid', 'Orchid')], default='default', help_text="Color theme for this user's workspace pages.", max_length=32),
        ),
    ]
