# Generated by Django 5.0.14 on 2026-07-18 15:30

from django.db import migrations, models


def migrate_open_to_pending(apps, schema_editor):
    CaseTask = apps.get_model("accounts", "CaseTask")
    MatterTask = apps.get_model("accounts", "MatterTask")
    CaseTask.objects.filter(status="open").update(status="pending")
    MatterTask.objects.filter(status="open").update(status="pending")


def migrate_pending_to_open(apps, schema_editor):
    CaseTask = apps.get_model("accounts", "CaseTask")
    MatterTask = apps.get_model("accounts", "MatterTask")
    CaseTask.objects.filter(status="pending").update(status="open")
    MatterTask.objects.filter(status="pending").update(status="open")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_bright_themes_diverse_fonts"),
    ]

    operations = [
        migrations.AddField(
            model_name="casetask",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Required when the assignee rejects the task.",
            ),
        ),
        migrations.AddField(
            model_name="casetask",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mattertask",
            name="rejection_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Required when the assignee rejects the task.",
            ),
        ),
        migrations.AddField(
            model_name="mattertask",
            name="responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="casetask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending acceptance"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("done", "Done"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="mattertask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending acceptance"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                    ("done", "Done"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
        migrations.RunPython(migrate_open_to_pending, migrate_pending_to_open),
    ]
