# Generated by Django 5.0.14 on 2026-07-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0020_task_accept_reject"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="notification_sound",
            field=models.BooleanField(
                default=True,
                help_text="Play a sound when new unread notifications arrive.",
            ),
        ),
    ]
