# Generated by Django 5.0.14 on 2026-07-18 18:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_employee_notification_sound'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=120)),
                ('judicial_officer', models.CharField(max_length=255)),
                ('court_room', models.CharField(blank=True, default='', max_length=120)),
                ('attendance_date', models.DateField()),
                ('presence', models.CharField(choices=[('present', 'PRESENT'), ('absent', 'ABSENT'), ('partial', 'PARTIAL')], default='present', max_length=16)),
                ('court_directions', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('next_action', models.TextField(blank=True, default='')),
                ('next_activity_type', models.CharField(blank=True, default='', max_length=120)),
                ('next_court_date', models.DateField(blank=True, null=True)),
                ('next_judicial_officer', models.CharField(blank=True, default='', max_length=255)),
                ('next_client_attendance', models.CharField(blank=True, choices=[('required', 'Client required'), ('not_required', 'Client not required'), ('optional', 'Client optional'), ('attended', 'Client attended'), ('did_not_attend', 'Client did not attend')], default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_attendances', to='accounts.litigationcase')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_court_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Court attendance',
                'verbose_name_plural': 'Court attendances',
                'ordering': ['-attendance_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourtAttendanceAdvocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advocate_name', models.CharField(max_length=255)),
                ('what_they_said', models.TextField(blank=True, default='')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advocates', to='accounts.courtattendance')),
            ],
            options={
                'verbose_name': 'Court attendance advocate',
                'verbose_name_plural': 'Court attendance advocates',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='CourtAttendanceBringUpItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('reminder_frequency', models.CharField(blank=True, choices=[('once', 'Once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('before_court', 'Before next court date'), ('monthly', 'Monthly')], default='', max_length=32)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('allocated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='court_bring_up_items', to=settings.AUTH_USER_MODEL)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bring_up_items', to='accounts.courtattendance')),
            ],
            options={
                'verbose_name': 'Court bring-up item',
                'verbose_name_plural': 'Court bring-up items',
                'ordering': ['sort_order', 'pk'],
            },
        ),
    ]
