# Generated by Django 5.0.14 on 2026-07-18 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_court_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatterAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(max_length=120)),
                ('attendance_date', models.DateField()),
                ('description', models.TextField(blank=True, default='')),
                ('next_action', models.TextField(blank=True, default='')),
                ('next_activity_type', models.CharField(blank=True, default='', max_length=120)),
                ('next_attendance_date', models.DateField(blank=True, null=True)),
                ('next_client_attendance', models.CharField(blank=True, choices=[('required', 'Client required'), ('not_required', 'Client not required'), ('optional', 'Client optional'), ('attended', 'Client attended'), ('did_not_attend', 'Client did not attend')], default='', max_length=32)),
                ('bring_update', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matter_attendances', to='accounts.nonlitigationmatter')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_matter_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Matter attendance',
                'verbose_name_plural': 'Matter attendances',
                'ordering': ['-attendance_date', '-created_at'],
            },
        ),
    ]
