# Generated by Django 5.0.14 on 2026-07-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_matter_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='casetask',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mattertask',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
