# Generated by Django 5.0.14 on 2026-07-19 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_matter_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Short summary of what this document is for.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='source',
            field=models.CharField(choices=[('google_doc', 'Google file'), ('uploaded', 'Uploaded file')], max_length=16),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ui_theme',
            field=models.CharField(blank=True, choices=[('default', 'Black & White'), ('product', 'Black & White'), ('firm_admin', 'Firm indigo'), ('managing_partner', 'Partner slate'), ('advocate', 'Advocate teal'), ('intern', 'Intern blue'), ('it_support', 'IT steel'), ('employee', 'Employee mauve'), ('midnight', 'Midnight'), ('graphite', 'Graphite'), ('cedar', 'Cedar'), ('cobalt', 'Cobalt'), ('olive', 'Olive'), ('copper', 'Copper'), ('arctic', 'Arctic'), ('espresso', 'Espresso'), ('jade', 'Jade'), ('marine', 'Marine'), ('sunrise', 'Sunrise'), ('citrus', 'Citrus'), ('azure', 'Azure'), ('emerald', 'Emerald'), ('saffron', 'Saffron'), ('flamingo', 'Flamingo'), ('electric', 'Electric'), ('ruby', 'Ruby'), ('lime', 'Lime'), ('orchid', 'Orchid')], default='default', help_text="Color theme for this user's workspace pages.", max_length=32),
        ),
        migrations.CreateModel(
            name='DocumentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('uploaded', 'Uploaded'), ('opened', 'Opened'), ('downloaded', 'Downloaded'), ('renamed', 'Renamed'), ('session_ended', 'Session ended')], max_length=32)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_activities', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='accounts.document')),
            ],
            options={
                'verbose_name': 'Document activity',
                'verbose_name_plural': 'Document activities',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DocumentOpenSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('ended_reason', models.CharField(blank=True, default='', max_length=32)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_open_sessions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_sessions', to='accounts.document')),
            ],
            options={
                'verbose_name': 'Document open session',
                'verbose_name_plural': 'Document open sessions',
                'ordering': ['-started_at', '-id'],
            },
        ),
    ]
