# Generated by Django 5.0.14 on 2026-07-19 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_document_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='document',
            name='content_preview',
            field=models.TextField(blank=True, default='', help_text='Latest plain-text preview synced from Google.'),
        ),
        migrations.AddField(
            model_name='document',
            name='content_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='drive_head_revision_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='document',
            name='drive_modified_at',
            field=models.DateTimeField(blank=True, help_text='Last modified time reported by Google Drive.', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='drive_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='documentactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('uploaded', 'Uploaded'), ('opened', 'Opened'), ('downloaded', 'Downloaded'), ('renamed', 'Renamed'), ('content_edited', 'Content edited'), ('session_ended', 'Session ended')], max_length=32),
        ),
        migrations.CreateModel(
            name='DocumentContentSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_id', models.CharField(blank=True, default='', max_length=128)),
                ('content_hash', models.CharField(blank=True, default='', max_length=64)),
                ('content_text', models.TextField(blank=True, default='')),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('modifier_name', models.CharField(blank=True, default='', max_length=255)),
                ('modifier_email', models.EmailField(blank=True, default='', max_length=254)),
                ('drive_modified_at', models.DateTimeField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_content_snapshots', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_snapshots', to='accounts.document')),
            ],
            options={
                'verbose_name': 'Document content snapshot',
                'verbose_name_plural': 'Document content snapshots',
                'ordering': ['-captured_at', '-id'],
            },
        ),
    ]
