# Generated by Django 5.0.14 on 2026-07-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_document_google_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='creating_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='editing_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='document',
            name='viewing_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentopensession',
            name='content_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentopensession',
            name='kind',
            field=models.CharField(choices=[('viewing', 'Viewing'), ('editing', 'Editing'), ('creating', 'Creating')], default='viewing', max_length=16),
        ),
    ]
