# Generated by Django 5.0.14 on 2026-07-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_document_time_analytics'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentopensession',
            name='baseline_char_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='documentopensession',
            name='baseline_content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='documentopensession',
            name='first_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentopensession',
            name='kind',
            field=models.CharField(choices=[('viewing', 'Viewing'), ('editing', 'Editing'), ('creating', 'Creating')], default='viewing', help_text='Auto-detected from Google content changes during the session.', max_length=16),
        ),
    ]
