# Generated by Django 5.0.14 on 2026-07-19 12:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_document_auto_detect_behavior'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmCompanyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, default='', max_length=255)),
                ('trading_name', models.CharField(blank=True, default='', help_text='Public / brand name if different from the legal name.', max_length=255)),
                ('registration_number', models.CharField(blank=True, default='', help_text='Business or company registration number.', max_length=100)),
                ('tax_pin', models.CharField(blank=True, default='', help_text='KRA PIN or equivalent tax identifier.', max_length=50, verbose_name='Tax PIN')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('website', models.URLField(blank=True, default='')),
                ('physical_address', models.TextField(blank=True, default='')),
                ('postal_address', models.CharField(blank=True, default='', max_length=255)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('country', models.CharField(blank=True, default='Kenya', max_length=120)),
                ('tagline', models.CharField(blank=True, default='', help_text='Short line used under the firm name where needed.', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_information_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company information',
                'verbose_name_plural': 'Company information',
            },
        ),
    ]
