# Generated by Django 5.0.14 on 2026-07-19 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_firm_company_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ui_density',
            field=models.CharField(blank=True, choices=[('comfortable', 'Comfortable'), ('compact', 'Compact'), ('airy', 'Airy')], default='comfortable', help_text="Spacing density for this user's workspace only.", max_length=16),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ui_font',
            field=models.CharField(blank=True, choices=[('plex', 'Plex Chambers'), ('source', 'Source Editorial'), ('manrope', 'Manrope Editorial'), ('figtree', 'Figtree Display'), ('sora', 'Sora Brief'), ('outfit', 'Outfit Literata'), ('jakarta', 'Jakarta Crimson'), ('syne', 'Syne Vollkorn'), ('epilogue', 'Epilogue Newsreader'), ('public', 'Public News'), ('space', 'Space Fraunces'), ('archivo', 'Archivo Playfair'), ('dm', 'DM Pair'), ('urbanist', 'Urbanist Cormorant'), ('bricolage', 'Bricolage Fraunces'), ('lexend', 'Lexend Spectral'), ('work', 'Work Zilla'), ('albert', 'Albert Cardo'), ('redhat', 'Red Hat Stack'), ('cabin', 'Cabin Alegreya')], default='plex', help_text="Font pairing for this user's workspace only.", max_length=32),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ui_theme',
            field=models.CharField(blank=True, choices=[('default', 'Black & White'), ('product', 'Black & White'), ('firm_admin', 'Firm indigo'), ('managing_partner', 'Partner slate'), ('advocate', 'Advocate teal'), ('intern', 'Intern blue'), ('it_support', 'IT steel'), ('employee', 'Employee mauve'), ('midnight', 'Midnight'), ('graphite', 'Graphite'), ('cedar', 'Cedar'), ('cobalt', 'Cobalt'), ('olive', 'Olive'), ('copper', 'Copper'), ('arctic', 'Arctic'), ('espresso', 'Espresso'), ('jade', 'Jade'), ('marine', 'Marine'), ('sunrise', 'Sunrise'), ('citrus', 'Citrus'), ('azure', 'Azure'), ('emerald', 'Emerald'), ('saffron', 'Saffron'), ('flamingo', 'Flamingo'), ('electric', 'Electric'), ('ruby', 'Ruby'), ('lime', 'Lime'), ('orchid', 'Orchid')], default='default', help_text="Color theme for this user's workspace only.", max_length=32),
        ),
        migrations.CreateModel(
            name='WebsiteTemplateSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_template', models.CharField(choices=[('sheria_centric', 'Sheria Centric website'), ('company', 'Company website')], default='sheria_centric', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='website_template_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Website template setting',
                'verbose_name_plural': 'Website template setting',
            },
        ),
    ]
