# Generated by Django 5.0.14 on 2026-07-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_website_template_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='about_me',
            field=models.TextField(blank=True, default='', help_text="Short personal bio shown on this user's profile."),
        ),
    ]
