# Generated by Django 5.0.14 on 2026-07-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_employee_blog_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmcompanyinformation',
            name='core_values',
            field=models.JSONField(blank=True, default=list, help_text='List of {"name": "...", "how": "..."} core value entries.'),
        ),
        migrations.AddField(
            model_name='firmcompanyinformation',
            name='founded_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='firmcompanyinformation',
            name='founded_year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='firmcompanyinformation',
            name='future_vision',
            field=models.TextField(blank=True, default='', help_text='Where the firm wants to be in 5–10 years.'),
        ),
        migrations.AddField(
            model_name='firmcompanyinformation',
            name='market_gap',
            field=models.TextField(blank=True, default='', help_text='Gap or need in the market that inspired the firm.'),
        ),
        migrations.AddField(
            model_name='firmcompanyinformation',
            name='milestone',
            field=models.TextField(blank=True, default='', help_text='One milestone worth mentioning.'),
        ),
        migrations.AddField(
            model_name='firmcompanyinformation',
            name='service_areas',
            field=models.TextField(blank=True, default='', help_text='Towns and cities the firm currently serves.'),
        ),
        migrations.AddField(
            model_name='firmcompanyinformation',
            name='value_proposition',
            field=models.CharField(blank=True, default='', help_text='One sentence: what you do, for whom, and the outcome.', max_length=500),
        ),
        migrations.AddField(
            model_name='firmcompanyinformation',
            name='visitor_feeling',
            field=models.CharField(blank=True, default='', help_text='One sentence: what a visitor should know or feel on landing.', max_length=500),
        ),
    ]
