# Generated by Django 5.0.14 on 2026-07-19 13:00

import accounts.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_firm_about_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmPracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Practice area')),
                ('summary', models.TextField(blank=True, default='', help_text='Short description of the work in this practice area.', verbose_name='What we do in this area')),
                ('details', models.TextField(blank=True, default='', help_text='Longer copy for the practice area page.', verbose_name='Detailed information')),
                ('rank', models.PositiveIntegerField(default=1, help_text='Lower numbers appear first (1 = highest priority).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_area_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Practice area',
                'verbose_name_plural': 'Practice areas',
                'ordering': ['rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FirmPracticeAreaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accounts.models.practice_area_image_upload_to)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('practice_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='accounts.firmpracticearea')),
            ],
            options={
                'verbose_name': 'Practice area image',
                'verbose_name_plural': 'Practice area images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
