# Generated by Django 5.0.14 on 2026-07-19 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_employee_blog_seo_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='employeeblogpost',
            new_name='accounts_em_status_454877_idx',
            old_name='accounts_em_status_7f2c1a_idx',
        ),
    ]
