# Generated by Django 5.0.14 on 2026-07-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_practice_gallery_slugs'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmcompanyinformation',
            name='facebook_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='firmcompanyinformation',
            name='instagram_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='firmcompanyinformation',
            name='linkedin_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='firmcompanyinformation',
            name='x_url',
            field=models.URLField(blank=True, default='', verbose_name='X (Twitter) URL'),
        ),
        migrations.AddField(
            model_name='firmcompanyinformation',
            name='youtube_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
