# Generated by Django 5.0.14 on 2026-07-20 10:32

import accounts.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_company_social_media_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmCompanyProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=accounts.models.company_profile_image_upload_to)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_images', to='accounts.firmcompanyinformation')),
            ],
            options={
                'verbose_name': 'Company profile image',
                'verbose_name_plural': 'Company profile images',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
