# Generated by Django 5.0.14 on 2026-07-20 11:45

from django.db import migrations, models


def forwards_issued_to_generated(apps, schema_editor):
    Invoice = apps.get_model("accounts", "Invoice")
    Invoice.objects.filter(status="issued").update(status="generated")


def backwards_generated_to_issued(apps, schema_editor):
    Invoice = apps.get_model("accounts", "Invoice")
    Invoice.objects.filter(status="generated").update(status="issued")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0046_invoice_model"),
    ]

    operations = [
        migrations.RunPython(
            forwards_issued_to_generated,
            backwards_generated_to_issued,
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("generated", "Generated"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="generated",
                max_length=20,
            ),
        ),
    ]
