# Generated by Django 5.0.14 on 2026-07-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_invoice_status_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='generated', max_length=20),
        ),
    ]
