# Generated by Django 5.0.14 on 2026-07-20 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_approved_by(apps, schema_editor):
    Invoice = apps.get_model("accounts", "Invoice")
    for invoice in Invoice.objects.filter(
        status="issued",
        approved_by__isnull=True,
        created_by__isnull=False,
    ):
        invoice.approved_by_id = invoice.created_by_id
        invoice.approved_at = invoice.updated_at
        invoice.save(update_fields=["approved_by", "approved_at"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_invoice_status_issued"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="approved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Employee who issued / approved this invoice for the client.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices_approved",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(backfill_approved_by, noop_reverse),
    ]
