# Generated by Django 5.0.14 on 2026-07-20 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_invoice_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('billing', 'Billing'), ('message', 'Message')], max_length=16)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True, default='')),
                ('target_url', models.CharField(help_text='Client portal path to open when the notification is clicked.', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('source_key', models.CharField(blank=True, default='', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.client')),
            ],
            options={
                'verbose_name': 'Client notification',
                'verbose_name_plural': 'Client notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='accounts_cl_recipie_f2665b_idx'), models.Index(fields=['recipient', 'category', '-created_at'], name='accounts_cl_recipie_9d2146_idx')],
            },
        ),
    ]
