# Generated by Django 5.0.14 on 2026-07-20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0050_client_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinanceSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allow_mpesa", models.BooleanField(default=True)),
                ("allow_bank_transfer", models.BooleanField(default=True)),
                ("allow_cash", models.BooleanField(default=True)),
                ("allow_cheque", models.BooleanField(default=False)),
                ("mpesa_paybill_enabled", models.BooleanField(default=False)),
                (
                    "mpesa_paybill_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "mpesa_paybill_account_label",
                    models.CharField(
                        blank=True,
                        default="Invoice number",
                        help_text="What clients enter as the account reference for Paybill.",
                        max_length=64,
                    ),
                ),
                ("mpesa_buy_goods_enabled", models.BooleanField(default=False)),
                (
                    "mpesa_till_number",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("mpesa_stk_enabled", models.BooleanField(default=False)),
                (
                    "mpesa_stk_channel",
                    models.CharField(
                        choices=[
                            ("paybill", "Paybill"),
                            ("buy_goods", "Buy Goods (Till)"),
                        ],
                        default="paybill",
                        max_length=16,
                    ),
                ),
                (
                    "mpesa_consumer_key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "mpesa_consumer_secret",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "mpesa_passkey",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "mpesa_shortcode",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Daraja BusinessShortCode. Defaults to Paybill or Till when blank.",
                        max_length=20,
                    ),
                ),
                ("mpesa_callback_url", models.URLField(blank=True, default="")),
                (
                    "mpesa_env",
                    models.CharField(
                        choices=[
                            ("sandbox", "Sandbox"),
                            ("production", "Production"),
                        ],
                        default="sandbox",
                        max_length=16,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finance_settings_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Finance settings",
                "verbose_name_plural": "Finance settings",
            },
        ),
    ]
