# Generated by Django 5.0.14 on 2026-07-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_finance_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Total amount received against this invoice.",
                max_digits=14,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="last_mpesa_receipt",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("generated", "Generated"),
                    ("issued", "Issued"),
                    ("partially_paid", "Partially paid"),
                    ("paid", "Paid"),
                    ("cancelled", "Cancelled"),
                ],
                default="generated",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MpesaStkRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checkout_request_id", models.CharField(max_length=128, unique=True)),
                (
                    "merchant_request_id",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=20)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("result_code", models.CharField(blank=True, default="", max_length=32)),
                (
                    "result_desc",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "mpesa_receipt",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("simulated", models.BooleanField(default=False)),
                ("payment_applied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stk_requests",
                        to="accounts.invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "M-Pesa STK request",
                "verbose_name_plural": "M-Pesa STK requests",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
