# Generated by Django 5.0.14 on 2026-07-21 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_invoice_payment_stk_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSearchJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('progress_label', models.CharField(blank=True, default='Queued', max_length=160)),
                ('filters', models.JSONField(default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error', models.CharField(blank=True, default='', max_length=500)),
                ('cancel_requested', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_search_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['requested_by', 'status', '-created_at'], name='accounts_ne_request_6ff729_idx')],
            },
        ),
    ]
