# Generated by Django 5.0.14 on 2026-07-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0054_news_watches"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemRequestMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=8)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("duration_ms", models.FloatField()),
                ("db_duration_ms", models.FloatField(default=0)),
                ("db_query_count", models.PositiveIntegerField(default=0)),
                ("response_bytes", models.PositiveBigIntegerField(default=0)),
                (
                    "user_role",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "error_type",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"],
                        name="system_metric_created_idx",
                    ),
                    models.Index(
                        fields=["endpoint", "-created_at"],
                        name="system_metric_route_idx",
                    ),
                    models.Index(
                        fields=["status_code", "-created_at"],
                        name="system_metric_status_idx",
                    ),
                ],
            },
        ),
    ]
