# Generated by Django 5.0.14 on 2026-07-21 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_newswatch_frequency'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('view', 'Page view'), ('cta_whatsapp', 'WhatsApp enquire'), ('cta_contact', 'Contact the firm'), ('related_click', 'Related article click')], max_length=32)),
                ('session_key', models.CharField(blank=True, default='', max_length=64)),
                ('referrer', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='web_events', to='accounts.employeeblogpost')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['post', 'event_type', '-created_at'], name='accounts_bl_post_id_156354_idx'), models.Index(fields=['post', '-created_at'], name='accounts_bl_post_id_451977_idx')],
            },
        ),
    ]
