# Generated by Django 5.0.14 on 2026-07-21 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_blog_post_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=False)),
                ('email_host', models.CharField(blank=True, default='', max_length=255)),
                ('email_port', models.PositiveIntegerField(default=587)),
                ('email_use_tls', models.BooleanField(default=True)),
                ('email_use_ssl', models.BooleanField(default=False)),
                ('email_host_user', models.CharField(blank=True, default='', max_length=255)),
                ('email_host_password', models.CharField(blank=True, default='', max_length=255)),
                ('email_from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('email_from_name', models.CharField(blank=True, default='', max_length=120)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('sms_provider', models.CharField(choices=[('none', 'Not set'), ('africastalking', "Africa's Talking"), ('twilio', 'Twilio')], default='none', max_length=32)),
                ('sms_username', models.CharField(blank=True, default='', help_text="Africa's Talking username (or Twilio Account SID).", max_length=120)),
                ('sms_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('sms_api_secret', models.CharField(blank=True, default='', help_text='Twilio Auth Token when using Twilio.', max_length=255)),
                ('sms_sender_id', models.CharField(blank=True, default='', help_text='Sender ID or from-number shown on SMS.', max_length=32)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('whatsapp_business_number', models.CharField(blank=True, default='', help_text='Business WhatsApp number for click-to-chat (e.g. +2547…).', max_length=32)),
                ('whatsapp_default_message', models.CharField(blank=True, default='', help_text='Pre-filled message when opening WhatsApp chat.', max_length=255)),
                ('whatsapp_api_enabled', models.BooleanField(default=False)),
                ('whatsapp_provider', models.CharField(choices=[('none', 'Not set'), ('meta', 'Meta Cloud API'), ('twilio', 'Twilio')], default='none', max_length=32)),
                ('whatsapp_api_token', models.CharField(blank=True, default='', max_length=512)),
                ('whatsapp_phone_number_id', models.CharField(blank=True, default='', help_text='Meta Phone Number ID, or Twilio WhatsApp sender.', max_length=120)),
                ('whatsapp_webhook_url', models.URLField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Communication settings',
                'verbose_name_plural': 'Communication settings',
            },
        ),
    ]
