# Generated by Django 5.0.14 on 2026-07-23 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_payroll_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='kra_pin_document',
            field=models.FileField(blank=True, help_text='KRA PIN certificate upload.', null=True, upload_to='clients/docs/kra/'),
        ),
        migrations.AddField(
            model_name='client',
            name='signed_instruction_note',
            field=models.FileField(blank=True, help_text='Signed instruction note from the client.', null=True, upload_to='clients/docs/instruction-notes/'),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_registration_document',
            field=models.FileField(blank=True, help_text='CR12 or company registration document.', null=True, upload_to='clients/docs/company/'),
        ),
    ]
