# Generated by Django 5.0.14 on 2026-07-23 13:55

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_client_kra_pin_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='drive_folder_id',
            field=models.CharField(blank=True, default='', help_text='Google Drive folder for this employee under Work/Employees Details/.', max_length=128),
        ),
        migrations.AddField(
            model_name='employee',
            name='drive_personal_details_folder_id',
            field=models.CharField(blank=True, default='', help_text='Google Drive Personal Details subfolder for this employee.', max_length=128),
        ),
        migrations.AddField(
            model_name='googledriveconnection',
            name='employees_details_folder_id',
            field=models.CharField(blank=True, default='', help_text='Google Drive Work/Employees Details folder.', max_length=128),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employment_contract',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.employee_personal_details_upload_to),
        ),
        migrations.AlterField(
            model_name='employee',
            name='kra_pin_certificate',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.employee_personal_details_upload_to),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id_or_passport',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.employee_personal_details_upload_to),
        ),
        migrations.AlterField(
            model_name='employee',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.employee_personal_details_upload_to),
        ),
    ]
