# Generated by Django 5.0.14 on 2026-07-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_employee_drive_personal_details_folders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='drive_folder_id',
            field=models.CharField(blank=True, default='', help_text='Google Drive folder for this employee under Work/.', max_length=128),
        ),
        migrations.AlterField(
            model_name='employee',
            name='drive_personal_details_folder_id',
            field=models.CharField(blank=True, default='', help_text='Google Drive Personal subfolder for this employee.', max_length=128),
        ),
        migrations.AlterField(
            model_name='googledriveconnection',
            name='employees_details_folder_id',
            field=models.CharField(blank=True, default='', help_text='Deprecated. Employee folders now live directly under Work/{Name}/Personal.', max_length=128),
        ),
    ]
