# Generated by Django 5.0.14 on 2026-07-23 14:01

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0069_employee_work_name_personal_folders'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='drive_personal_documents_folder_id',
            field=models.CharField(blank=True, default='', help_text='Google Drive Personal Documents subfolder for this client.', max_length=128),
        ),
        migrations.AlterField(
            model_name='client',
            name='alien_document',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.client_personal_documents_upload_to),
        ),
        migrations.AlterField(
            model_name='client',
            name='business_document',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.client_personal_documents_upload_to),
        ),
        migrations.AlterField(
            model_name='client',
            name='company_registration_document',
            field=models.FileField(blank=True, help_text='CR12 or company registration document.', null=True, upload_to=accounts.models.client_personal_documents_upload_to),
        ),
        migrations.AlterField(
            model_name='client',
            name='identification_document',
            field=models.FileField(blank=True, null=True, upload_to=accounts.models.client_personal_documents_upload_to),
        ),
        migrations.AlterField(
            model_name='client',
            name='kra_pin_document',
            field=models.FileField(blank=True, help_text='KRA PIN certificate upload.', null=True, upload_to=accounts.models.client_personal_documents_upload_to),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.client_personal_documents_upload_to),
        ),
        migrations.AlterField(
            model_name='client',
            name='signed_instruction_note',
            field=models.FileField(blank=True, help_text='Signed instruction note from the client.', null=True, upload_to=accounts.models.client_personal_documents_upload_to),
        ),
    ]
