# Generated by Django 5.0.14 on 2026-07-23 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_client_personal_documents_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='linked_client',
            field=models.ForeignKey(blank=True, help_text='Registered client this document is linked to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_documents', to='accounts.client'),
        ),
        migrations.AddField(
            model_name='document',
            name='linked_client_email',
            field=models.EmailField(blank=True, default='', help_text='Optional email when linking to an unregistered client.', max_length=254),
        ),
        migrations.AddField(
            model_name='document',
            name='linked_client_name',
            field=models.CharField(blank=True, default='', help_text='Name when linking to an unregistered client.', max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='linked_client_phone',
            field=models.CharField(blank=True, default='', help_text='Phone when linking to an unregistered client.', max_length=32),
        ),
    ]
