# Generated by Django 5.0.14 on 2026-07-23 14:25

from django.db import migrations, models


REMOVED_CLIENT_ATTENDANCE = ("attended", "did_not_attend")


def clear_removed_client_attendance(apps, schema_editor):
    CourtAttendance = apps.get_model("accounts", "CourtAttendance")
    CourtAttendance.objects.filter(
        next_client_attendance__in=REMOVED_CLIENT_ATTENDANCE
    ).update(next_client_attendance="", virtual_link="")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0071_document_linked_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="courtattendance",
            name="virtual_link",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="document",
            name="party_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Party type this document relates to (case or matter party roles).",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="courtattendance",
            name="next_client_attendance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("required", "Client required"),
                    ("not_required", "Client not required"),
                    ("optional", "Client optional"),
                    ("virtual", "Virtual"),
                ],
                default="",
                max_length=32,
            ),
        ),
        migrations.RunPython(clear_removed_client_attendance, noop_reverse),
    ]
