# Generated by Django 5.0.14 on 2026-07-23 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


REMOVED_CLIENT_ATTENDANCE = ("attended", "did_not_attend")


def cleanup_matter_attendance(apps, schema_editor):
    MatterAttendance = apps.get_model("accounts", "MatterAttendance")
    MatterAttendanceBringUpItem = apps.get_model(
        "accounts", "MatterAttendanceBringUpItem"
    )
    MatterAttendance.objects.filter(
        next_client_attendance__in=REMOVED_CLIENT_ATTENDANCE
    ).update(next_client_attendance="")

    for attendance in MatterAttendance.objects.exclude(bring_update="").iterator():
        text = (attendance.bring_update or "").strip()
        if not text:
            continue
        if MatterAttendanceBringUpItem.objects.filter(
            attendance_id=attendance.pk
        ).exists():
            continue
        MatterAttendanceBringUpItem.objects.create(
            attendance_id=attendance.pk,
            description=text,
            sort_order=0,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0075_mattertask_access_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="matterattendance",
            name="contact_person",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="matterattendance",
            name="location",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="matterattendance",
            name="next_contact_person",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="matterattendance",
            name="outcome_notes",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="matterattendance",
            name="presence",
            field=models.CharField(
                choices=[
                    ("present", "PRESENT"),
                    ("absent", "ABSENT"),
                    ("partial", "PARTIAL"),
                ],
                default="present",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="matterattendance",
            name="virtual_link",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.CreateModel(
            name="MatterAttendanceBringUpItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "reminder_frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("once", "Once"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("before_attendance", "Before next attendance"),
                            ("monthly", "Monthly"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "allocated_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matter_bring_up_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bring_up_items",
                        to="accounts.matterattendance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matter bring-up item",
                "verbose_name_plural": "Matter bring-up items",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="MatterAttendanceQuorumMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("participant_name", models.CharField(max_length=255)),
                ("what_they_said", models.TextField(blank=True, default="")),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "attendance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quorum_members",
                        to="accounts.matterattendance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Matter attendance quorum member",
                "verbose_name_plural": "Matter attendance quorum members",
                "ordering": ["sort_order", "pk"],
            },
        ),
        migrations.RunPython(cleanup_matter_attendance, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="matterattendance",
            name="next_client_attendance",
            field=models.CharField(
                blank=True,
                choices=[
                    ("required", "Client required"),
                    ("not_required", "Client not required"),
                    ("optional", "Client optional"),
                    ("virtual", "Virtual"),
                ],
                default="",
                max_length=32,
            ),
        ),
    ]
