# Generated by Django 5.0.14 on 2026-07-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0076_matter_attendance_parity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ui_theme',
            field=models.CharField(blank=True, choices=[('default', 'Black & White'), ('product', 'Black & White'), ('firm_admin', 'Firm indigo'), ('managing_partner', 'Partner slate'), ('advocate', 'Advocate teal'), ('intern', 'Intern blue'), ('it_support', 'IT steel'), ('employee', 'Employee mauve'), ('midnight', 'Midnight'), ('graphite', 'Graphite'), ('cedar', 'Cedar'), ('cobalt', 'Cobalt'), ('olive', 'Olive'), ('copper', 'Copper'), ('arctic', 'Arctic'), ('espresso', 'Espresso'), ('jade', 'Jade'), ('marine', 'Marine'), ('sunrise', 'Sunrise'), ('citrus', 'Citrus'), ('azure', 'Azure'), ('emerald', 'Emerald'), ('saffron', 'Saffron'), ('flamingo', 'Flamingo'), ('electric', 'Electric'), ('ruby', 'Ruby'), ('lime', 'Lime'), ('orchid', 'Orchid'), ('violet_glow', 'Violet glow'), ('teal_matter', 'Teal matter'), ('orange_brief', 'Orange brief'), ('rose_seal', 'Rose seal'), ('blue_docket', 'Blue docket'), ('verdant_leaf', 'Verdant leaf'), ('amethyst_file', 'Amethyst file'), ('indigo_list', 'Indigo list'), ('ember_court', 'Ember court'), ('fuchsia_client', 'Fuchsia client'), ('cyan_harbor', 'Cyan harbor'), ('blush_advice', 'Blush advice')], default='default', help_text="Color theme for this user's workspace only.", max_length=32),
        ),
    ]
