# Generated by Django 5.0.14 on 2026-07-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0077_matter_desk_themes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ui_theme',
            field=models.CharField(blank=True, choices=[('default', 'Black & White'), ('product', 'Black & White'), ('firm_admin', 'Firm indigo'), ('managing_partner', 'Partner slate'), ('advocate', 'Advocate teal'), ('intern', 'Intern blue'), ('it_support', 'IT steel'), ('employee', 'Employee mauve'), ('midnight', 'Midnight'), ('graphite', 'Graphite'), ('cedar', 'Cedar'), ('cobalt', 'Cobalt'), ('olive', 'Olive'), ('copper', 'Copper'), ('arctic', 'Arctic'), ('espresso', 'Espresso'), ('jade', 'Jade'), ('marine', 'Marine'), ('sunrise', 'Sunrise'), ('citrus', 'Citrus'), ('azure', 'Azure'), ('emerald', 'Emerald'), ('saffron', 'Saffron'), ('flamingo', 'Flamingo'), ('electric', 'Electric'), ('ruby', 'Ruby'), ('lime', 'Lime'), ('orchid', 'Orchid'), ('violet_glow', 'Chamber slate'), ('teal_matter', 'Matter teal'), ('orange_brief', 'Brief bronze'), ('rose_seal', 'Seal burgundy'), ('blue_docket', 'Docket steel'), ('verdant_leaf', 'Sage verdant'), ('amethyst_file', 'File plum'), ('indigo_list', 'List indigo'), ('ember_court', 'Court terracotta'), ('fuchsia_client', 'Client mauve'), ('cyan_harbor', 'Harbor slate'), ('blush_advice', 'Advice rose')], default='default', help_text="Color theme for this user's workspace only.", max_length=32),
        ),
    ]
