# Generated by Django 5.0.14 on 2026-07-23 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0078_practice_accent_theme_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ui_theme',
            field=models.CharField(blank=True, choices=[('default', 'Black & White'), ('product', 'Black & White'), ('firm_admin', 'Firm indigo'), ('managing_partner', 'Partner slate'), ('advocate', 'Advocate teal'), ('intern', 'Intern blue'), ('it_support', 'IT steel'), ('employee', 'Employee mauve'), ('midnight', 'Midnight'), ('graphite', 'Graphite'), ('cedar', 'Cedar'), ('cobalt', 'Cobalt'), ('olive', 'Olive'), ('copper', 'Copper'), ('arctic', 'Arctic'), ('espresso', 'Espresso'), ('jade', 'Jade'), ('marine', 'Marine'), ('sunrise', 'Sunrise'), ('citrus', 'Citrus'), ('azure', 'Azure'), ('emerald', 'Emerald'), ('saffron', 'Saffron'), ('flamingo', 'Flamingo'), ('electric', 'Electric'), ('ruby', 'Ruby'), ('lime', 'Lime'), ('orchid', 'Orchid'), ('violet_glow', 'Aurora'), ('teal_matter', 'Cascade'), ('orange_brief', 'Copper'), ('rose_seal', 'Garnet'), ('blue_docket', 'Atlas'), ('verdant_leaf', 'Grove'), ('amethyst_file', 'Violet'), ('indigo_list', 'Ink'), ('ember_court', 'Ember'), ('fuchsia_client', 'Berry'), ('cyan_harbor', 'Glacier'), ('blush_advice', 'Blush')], default='default', help_text="Color theme for this user's workspace only.", max_length=32),
        ),
    ]
