# Generated by Django 5.0.14 on 2026-07-23 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0079_modern_studio_theme_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ui_theme',
            field=models.CharField(blank=True, choices=[('default', 'Black & White'), ('product', 'Black & White'), ('firm_admin', 'Firm indigo'), ('managing_partner', 'Partner slate'), ('advocate', 'Advocate teal'), ('intern', 'Intern blue'), ('it_support', 'IT steel'), ('employee', 'Employee mauve'), ('midnight', 'Midnight'), ('graphite', 'Graphite'), ('cedar', 'Cedar'), ('cobalt', 'Cobalt'), ('olive', 'Olive'), ('copper', 'Copper'), ('arctic', 'Arctic'), ('espresso', 'Espresso'), ('jade', 'Jade'), ('marine', 'Marine'), ('sunrise', 'Sunrise'), ('citrus', 'Citrus'), ('azure', 'Azure'), ('emerald', 'Emerald'), ('saffron', 'Saffron'), ('flamingo', 'Flamingo'), ('electric', 'Electric'), ('ruby', 'Ruby'), ('lime', 'Lime'), ('orchid', 'Orchid'), ('violet_glow', 'Aurora'), ('teal_matter', 'Cascade'), ('orange_brief', 'Copper'), ('rose_seal', 'Garnet'), ('blue_docket', 'Atlas'), ('verdant_leaf', 'Grove'), ('amethyst_file', 'Violet'), ('indigo_list', 'Ink'), ('ember_court', 'Ember'), ('fuchsia_client', 'Berry'), ('cyan_harbor', 'Glacier'), ('blush_advice', 'Blush')], default='default', help_text="Color theme for this user's workspace. 'default' follows the company theme.", max_length=32),
        ),
        migrations.CreateModel(
            name='CompanyThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_ui_theme', models.CharField(choices=[('default', 'Black & White'), ('product', 'Black & White'), ('firm_admin', 'Firm indigo'), ('managing_partner', 'Partner slate'), ('advocate', 'Advocate teal'), ('intern', 'Intern blue'), ('it_support', 'IT steel'), ('employee', 'Employee mauve'), ('midnight', 'Midnight'), ('graphite', 'Graphite'), ('cedar', 'Cedar'), ('cobalt', 'Cobalt'), ('olive', 'Olive'), ('copper', 'Copper'), ('arctic', 'Arctic'), ('espresso', 'Espresso'), ('jade', 'Jade'), ('marine', 'Marine'), ('sunrise', 'Sunrise'), ('citrus', 'Citrus'), ('azure', 'Azure'), ('emerald', 'Emerald'), ('saffron', 'Saffron'), ('flamingo', 'Flamingo'), ('electric', 'Electric'), ('ruby', 'Ruby'), ('lime', 'Lime'), ('orchid', 'Orchid'), ('violet_glow', 'Aurora'), ('teal_matter', 'Cascade'), ('orange_brief', 'Copper'), ('rose_seal', 'Garnet'), ('blue_docket', 'Atlas'), ('verdant_leaf', 'Grove'), ('amethyst_file', 'Violet'), ('indigo_list', 'Ink'), ('ember_court', 'Ember'), ('fuchsia_client', 'Berry'), ('cyan_harbor', 'Glacier'), ('blush_advice', 'Blush')], default='default', help_text='Default color theme for workspace pages when a user has not chosen a personal theme.', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_theme_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company theme setting',
                'verbose_name_plural': 'Company theme setting',
            },
        ),
    ]
