# Generated by Django 5.0.14 on 2026-07-24 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0080_company_theme_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyExpenseAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Expense account name')),
                ('company_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('payment_methods', models.JSONField(blank=True, default=list, help_text='List of payment method keys used for this expense account.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_expense_accounts_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company expense account',
                'verbose_name_plural': 'Company expense accounts',
                'ordering': ['name', 'id'],
            },
        ),
    ]
