# Generated by Django 5.0.14 on 2026-07-24 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0086_client_account_topup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyexpenseaccount',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Account name'),
        ),
    ]
