# Generated by Django 5.0.14 on 2026-07-24 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0091_companyexpensepayment_payroll'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('outstanding', 'Outstanding'), ('recovered', 'Recovered')], default='outstanding', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_advances', to=settings.AUTH_USER_MODEL)),
                ('payroll_run', models.ForeignKey(help_text='Registered payroll run this advance will be recovered from.', on_delete=django.db.models.deletion.PROTECT, related_name='salary_advances', to='accounts.payrollrun')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_advances_recorded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee advance',
                'verbose_name_plural': 'Employee advances',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
