# Generated by Django 5.0.14 on 2026-07-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0092_employee_advance'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeadvance',
            name='reason',
            field=models.CharField(choices=[('medical', 'Medical emergency'), ('school_fees', 'School fees'), ('rent', 'Rent / housing'), ('family', 'Family emergency'), ('travel', 'Travel'), ('utilities', 'Utilities / bills'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
