# Generated by Django 5.0.14 on 2026-07-24 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0093_employee_advance_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCashExpenseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('office_supplies', 'Office supplies'), ('transport', 'Transport / travel'), ('utilities', 'Utilities'), ('communication', 'Communication'), ('court_fees', 'Court fees'), ('filing_fees', 'Filing fees'), ('professional_fees', 'Professional fees'), ('payroll', 'Payroll'), ('staff_welfare', 'Staff welfare'), ('maintenance', 'Maintenance / repairs'), ('bank_charges', 'Bank charges'), ('rent', 'Rent'), ('other', 'Other')], default='other', max_length=32)),
                ('description', models.TextField(help_text='What this petty cash expense covers.')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(help_text='Employee the expense is claimed for.', on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_expense_requests', to=settings.AUTH_USER_MODEL)),
                ('expense_payment', models.OneToOneField(blank=True, help_text='Ledger payment created when this request is approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_request', to='accounts.companyexpensepayment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_expense_requests_reviewed', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_expense_requests_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Petty cash expense request',
                'verbose_name_plural': 'Petty cash expense requests',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
