# Generated by Django 5.0.14 on 2026-07-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0100_employee_digital_stamp_setting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydigitalstampsetting',
            name='show_approver',
            field=models.BooleanField(default=True, help_text='Show the company name line on the stamp.'),
        ),
    ]
