# Generated by Django 5.0.14 on 2026-07-24 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0101_alter_company_stamp_show_approver_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(
                blank=True,
                help_text="Optional payment due date.",
                null=True,
            ),
        ),
    ]
