# Generated by Django 5.0.14 on 2026-07-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0108_employee_notification_browser'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ui_density',
            field=models.CharField(blank=True, choices=[('comfortable', 'Comfortable'), ('compact', 'Compact'), ('airy', 'Airy')], default='comfortable', help_text="Spacing density for this client's portal only.", max_length=16),
        ),
        migrations.AddField(
            model_name='client',
            name='ui_font',
            field=models.CharField(blank=True, choices=[('plex', 'Plex Chambers'), ('source', 'Source Editorial'), ('manrope', 'Manrope Editorial'), ('figtree', 'Figtree Display'), ('sora', 'Sora Brief'), ('outfit', 'Outfit Literata'), ('jakarta', 'Jakarta Crimson'), ('syne', 'Syne Vollkorn'), ('epilogue', 'Epilogue Newsreader'), ('public', 'Public News'), ('space', 'Space Fraunces'), ('archivo', 'Archivo Playfair'), ('dm', 'DM Pair'), ('urbanist', 'Urbanist Cormorant'), ('bricolage', 'Bricolage Fraunces'), ('lexend', 'Lexend Spectral'), ('work', 'Work Zilla'), ('albert', 'Albert Cardo'), ('redhat', 'Red Hat Stack'), ('cabin', 'Cabin Alegreya')], default='plex', help_text="Font pairing for this client's portal only.", max_length=32),
        ),
        migrations.AddField(
            model_name='client',
            name='ui_theme',
            field=models.CharField(blank=True, choices=[('default', 'Black & White'), ('product', 'Black & White'), ('firm_admin', 'Firm indigo'), ('managing_partner', 'Partner slate'), ('advocate', 'Advocate teal'), ('intern', 'Intern blue'), ('it_support', 'IT steel'), ('employee', 'Employee mauve'), ('midnight', 'Midnight'), ('graphite', 'Graphite'), ('cedar', 'Cedar'), ('cobalt', 'Cobalt'), ('olive', 'Olive'), ('copper', 'Copper'), ('arctic', 'Arctic'), ('espresso', 'Espresso'), ('jade', 'Jade'), ('marine', 'Marine'), ('sunrise', 'Sunrise'), ('citrus', 'Citrus'), ('azure', 'Azure'), ('emerald', 'Emerald'), ('saffron', 'Saffron'), ('flamingo', 'Flamingo'), ('electric', 'Electric'), ('ruby', 'Ruby'), ('lime', 'Lime'), ('orchid', 'Orchid'), ('violet_glow', 'Aurora'), ('teal_matter', 'Cascade'), ('orange_brief', 'Copper'), ('rose_seal', 'Garnet'), ('blue_docket', 'Atlas'), ('verdant_leaf', 'Grove'), ('amethyst_file', 'Violet'), ('indigo_list', 'Ink'), ('ember_court', 'Ember'), ('fuchsia_client', 'Berry'), ('cyan_harbor', 'Glacier'), ('blush_advice', 'Blush')], default='default', help_text="Color theme for this client's portal. 'default' follows the company theme.", max_length=32),
        ),
        migrations.AlterField(
            model_name='employee',
            name='drive_folder_id',
            field=models.CharField(blank=True, default='', help_text='Google Drive folder for this employee under Employees/.', max_length=128),
        ),
        migrations.AlterField(
            model_name='googledriveconnection',
            name='employees_details_folder_id',
            field=models.CharField(blank=True, default='', help_text='Deprecated. Employee folders now live directly under Employees/{Name}/Personal.', max_length=128),
        ),
    ]
