# Generated by Django 5.0.14 on 2026-07-25 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0109_client_ui_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationsettings',
            name='whatsapp_webhook_verify_token',
            field=models.CharField(blank=True, default='', help_text='Verify token Meta sends during webhook subscription.', max_length=120),
        ),
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(db_index=True, max_length=32, unique=True)),
                ('display_name', models.CharField(blank=True, default='', max_length=180)),
                ('unread_count', models.PositiveIntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_message_preview', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='accounts.client')),
            ],
            options={
                'verbose_name': 'WhatsApp conversation',
                'verbose_name_plural': 'WhatsApp conversations',
                'ordering': ['-last_message_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', 'Inbound'), ('out', 'Outbound')], max_length=8)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('received', 'Received')], default='queued', max_length=16)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', help_text='Meta wamid or provider message id.', max_length=120)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.whatsappconversation')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WhatsApp message',
                'verbose_name_plural': 'WhatsApp messages',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['conversation', 'created_at'], name='accounts_wh_convers_96b215_idx')],
            },
        ),
    ]
