# Generated by Django 5.0.14 on 2026-07-30 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0110_whatsapp_inbox_and_verify_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydigitalstampsetting',
            name='accent',
            field=models.CharField(choices=[('ink', 'Stamp ink blue'), ('forest', 'Forest'), ('navy', 'Navy'), ('charcoal', 'Charcoal'), ('burgundy', 'Burgundy'), ('teal', 'Teal'), ('gold', 'Gold')], default='forest', help_text='Accent colour for the stamp ink and borders.', max_length=32),
        ),
        migrations.AlterField(
            model_name='companydigitalstampsetting',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic ring'), ('advocate', 'Advocate block'), ('square', 'Square seal'), ('oval', 'Oval seal'), ('badge', 'Shield badge'), ('ribbon', 'Ribbon banner'), ('wax', 'Wax stamp')], default='classic', help_text='Digital stamp layout sample used on invoices and receipts.', max_length=32),
        ),
        migrations.AlterField(
            model_name='employeedigitalstampsetting',
            name='accent',
            field=models.CharField(choices=[('ink', 'Stamp ink blue'), ('forest', 'Forest'), ('navy', 'Navy'), ('charcoal', 'Charcoal'), ('burgundy', 'Burgundy'), ('teal', 'Teal'), ('gold', 'Gold')], default='navy', help_text='Accent colour for the stamp ink and borders.', max_length=32),
        ),
        migrations.AlterField(
            model_name='employeedigitalstampsetting',
            name='template',
            field=models.CharField(choices=[('classic', 'Classic ring'), ('advocate', 'Advocate block'), ('square', 'Square seal'), ('oval', 'Oval seal'), ('badge', 'Shield badge'), ('ribbon', 'Ribbon banner'), ('wax', 'Wax stamp')], default='classic', help_text='Personal digital stamp layout sample.', max_length=32),
        ),
    ]
