# Generated by Django 5.0.14 on 2026-07-30 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0111_stamp_advocate_template_and_ink_accent'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydigitalstampsetting',
            name='stamp_image',
            field=models.ImageField(blank=True, help_text="Scan or photo of the firm's physical stamp. Used on documents instead of the designed stamp while it is uploaded.", null=True, upload_to='stamps/company/'),
        ),
        migrations.AddField(
            model_name='employeedigitalstampsetting',
            name='stamp_image',
            field=models.ImageField(blank=True, help_text='Scan or photo of your physical stamp. Used on documents instead of the designed stamp while it is uploaded.', null=True, upload_to='stamps/employee/'),
        ),
    ]
