# Generated by Django 5.0.14 on 2026-07-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0115_correct_invoice_tax_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydigitalsignaturesetting',
            name='signature_image',
            field=models.ImageField(blank=True, help_text='Signature sketched on the signature pad, or an uploaded scan. Used on documents instead of the designed signature block.', null=True, upload_to='signatures/company/'),
        ),
    ]
