# Generated by Django 5.0.14 on 2026-07-30 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0117_employee_my_templates_folders'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDigitalSignatureSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', models.CharField(choices=[('classic', 'Classic line'), ('script', 'Script flourish'), ('formal', 'Formal block'), ('monogram', 'Monogram mark'), ('stacked', 'Stacked authority'), ('compact', 'Compact strip')], default='classic', help_text='Personal digital signature layout sample.', max_length=32)),
                ('accent', models.CharField(choices=[('forest', 'Forest'), ('navy', 'Navy'), ('charcoal', 'Charcoal'), ('burgundy', 'Burgundy'), ('teal', 'Teal'), ('gold', 'Gold')], default='navy', help_text='Accent colour for the signature ink and rules.', max_length=32)),
                ('default_title', models.CharField(blank=True, default='Authorized Signatory', help_text='Title / capacity shown when you have no role on file.', max_length=120)),
                ('signature_image', models.ImageField(blank=True, help_text='Signature sketched on the signature pad, or an uploaded scan. Used on your documents instead of the designed signature block.', null=True, upload_to='signatures/employee/')),
                ('show_firm_name', models.BooleanField(default=True, help_text='Show the firm display name on the signature block.')),
                ('show_name', models.BooleanField(default=True, help_text='Show your name when available.')),
                ('show_title', models.BooleanField(default=True, help_text='Show your title / capacity.')),
                ('show_date', models.BooleanField(default=True, help_text='Show the signature date when available.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_signature_setting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee digital signature setting',
                'verbose_name_plural': 'Employee digital signature settings',
            },
        ),
    ]
