# Generated by Django 5.0.14 on 2026-07-30 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0118_employeedigitalsignaturesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('signature', 'Signature'), ('stamp', 'Stamp')], max_length=16)),
                ('page', models.PositiveSmallIntegerField(default=1)),
                ('x_percent', models.FloatField(default=60.0)),
                ('y_percent', models.FloatField(default=70.0)),
                ('width_percent', models.FloatField(default=24.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='accounts.document')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_marks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document mark',
                'verbose_name_plural': 'Document marks',
                'ordering': ['kind', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='documentmark',
            constraint=models.UniqueConstraint(fields=('document', 'employee', 'kind'), name='document_mark_unique_per_signatory'),
        ),
    ]
