# Generated by Django 5.0.14 on 2026-07-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0119_document_marks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentactivity',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('uploaded', 'Uploaded'), ('opened', 'Opened'), ('downloaded', 'Downloaded'), ('renamed', 'Renamed'), ('content_edited', 'Content edited'), ('session_ended', 'Session ended'), ('mark_placed', 'Stamp / signature placed'), ('mark_removed', 'Stamp / signature removed')], max_length=32),
        ),
    ]
