# Generated by Django 5.0.14 on 2026-07-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0120_document_mark_activity_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationsettings',
            name='cpanel_api_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='communicationsettings',
            name='cpanel_host',
            field=models.CharField(blank=True, default='', help_text='cPanel server hostname, e.g. server.yourhost.com.', max_length=255),
        ),
        migrations.AddField(
            model_name='communicationsettings',
            name='cpanel_port',
            field=models.PositiveIntegerField(default=2083),
        ),
        migrations.AddField(
            model_name='communicationsettings',
            name='cpanel_username',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='communicationsettings',
            name='work_email_domain',
            field=models.CharField(blank=True, default='', help_text='Domain new work addresses are created on, e.g. yourfirm.com.', max_length=255),
        ),
        migrations.AddField(
            model_name='communicationsettings',
            name='work_email_provisioning_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='communicationsettings',
            name='work_email_quota_mb',
            field=models.PositiveIntegerField(default=1024, help_text='Mailbox size in MB. Use 0 for unlimited.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_email',
            field=models.EmailField(blank=True, help_text='Firm mailbox created on approval, e.g. first.last@firm.com.', max_length=254, null=True),
        ),
    ]
