# Generated by Django 5.0.14 on 2026-07-30 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0121_communicationsettings_cpanel_api_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworksession',
            name='logout_kind',
            field=models.CharField(blank=True, choices=[('manual', 'Signed out'), ('expired', 'Session expired'), ('replaced', 'New login'), ('suspended', 'Account suspended')], default='', max_length=16),
        ),
    ]
