# Generated by Django 5.0.14 on 2026-07-30 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0122_employee_work_session_logout_kind_suspended'),
    ]

    operations = [
        migrations.AddField(
            model_name='communicationsettings',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='communicationsettings',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communication_settings_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
