# Generated by Django 5.0.14 on 2026-07-30 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0123_communicationsettings_verified_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=16)),
                ('from_identity', models.CharField(blank=True, default='', help_text='Work email or work phone the message was sent from.', max_length=255)),
                ('to_address', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=16)),
                ('error_message', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications_sent', to=settings.AUTH_USER_MODEL)),
                ('to_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_communications', to='accounts.client')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='communications_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employee communication',
                'verbose_name_plural': 'Employee communications',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['sender', 'channel', '-created_at'], name='accounts_em_sender__083112_idx')],
            },
        ),
    ]
