# Generated by Django 5.0.14 on 2026-07-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0124_employeecommunication'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='work_email_password_encrypted',
            field=models.TextField(blank=True, default='', help_text='Encrypted cPanel mailbox password for IMAP/SMTP in Messages.'),
        ),
    ]
