# Generated by Django 5.0.14 on 2026-09-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0125_employee_work_email_password_encrypted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='personal_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
