# Generated by Django 5.0.14 on 2026-09-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0126_employee_personal_email_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_b2b_consumer_key',
            field=models.CharField(blank=True, default='', help_text='Leave blank to reuse the STK Push consumer key.', max_length=255),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_b2b_consumer_secret',
            field=models.CharField(blank=True, default='', help_text='Leave blank to reuse the STK Push consumer secret.', max_length=255),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_b2b_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_b2b_initiator_name',
            field=models.CharField(blank=True, default='', help_text='M-Pesa API operator username from the Org Portal.', max_length=64),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_b2b_result_url',
            field=models.URLField(blank=True, default='', help_text='HTTPS URL Safaricom POSTs the transfer result to.'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_b2b_security_credential',
            field=models.TextField(blank=True, default='', help_text='RSA-encrypted initiator password from the Daraja Security Credential tool.'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_b2b_shortcode',
            field=models.CharField(blank=True, default='', help_text='Source shortcode (PartyA). Defaults to Paybill when blank.', max_length=20),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_b2b_timeout_url',
            field=models.URLField(blank=True, default='', help_text='HTTPS URL Safaricom POSTs to when the transfer times out.'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_b2b_to_paybill',
            field=models.BooleanField(default=True, help_text='Allow transfers to another Paybill number.'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_b2b_to_phone',
            field=models.BooleanField(default=True, help_text='Allow transfers to a Safaricom phone number (B2C).'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_b2b_to_till',
            field=models.BooleanField(default=True, help_text='Allow transfers to a Buy Goods Till.'),
        ),
    ]
