# Generated by Django 5.0.14 on 2026-09-17 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0127_finance_settings_b2b_transfers'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_float_charges',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last known Charges Paid Account balance from Safaricom.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_float_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_float_conversation_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_float_raw',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_float_utility',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last known Utility Account balance from Safaricom.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='mpesa_float_working',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last known Working Account balance from Safaricom.', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='companyexpensepayment',
            name='expense_type',
            field=models.CharField(choices=[('office_supplies', 'Office supplies'), ('transport', 'Transport / travel'), ('utilities', 'Utilities'), ('communication', 'Communication'), ('court_fees', 'Court fees'), ('filing_fees', 'Filing fees'), ('professional_fees', 'Professional fees'), ('payroll', 'Payroll'), ('staff_welfare', 'Staff welfare'), ('maintenance', 'Maintenance / repairs'), ('bank_charges', 'Bank charges'), ('rent', 'Rent'), ('mpesa_transfer', 'M-Pesa transfer'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='pettycashexpenserequest',
            name='expense_type',
            field=models.CharField(choices=[('office_supplies', 'Office supplies'), ('transport', 'Transport / travel'), ('utilities', 'Utilities'), ('communication', 'Communication'), ('court_fees', 'Court fees'), ('filing_fees', 'Filing fees'), ('professional_fees', 'Professional fees'), ('payroll', 'Payroll'), ('staff_welfare', 'Staff welfare'), ('maintenance', 'Maintenance / repairs'), ('bank_charges', 'Bank charges'), ('rent', 'Rent'), ('mpesa_transfer', 'M-Pesa transfer'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.CreateModel(
            name='MpesaB2bTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_type', models.CharField(choices=[('paybill', 'Paybill'), ('till', 'Buy Goods Till'), ('phone', 'Phone number')], max_length=16)),
                ('party_b', models.CharField(help_text='Destination Paybill, Till, or MSISDN.', max_length=20)),
                ('account_reference', models.CharField(blank=True, default='', help_text='Account reference for Paybill destinations.', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remarks', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('failed', 'Failed'), ('timed_out', 'Timed out')], db_index=True, default='pending', max_length=16)),
                ('conversation_id', models.CharField(blank=True, default='', max_length=64)),
                ('originator_conversation_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=64)),
                ('result_code', models.CharField(blank=True, default='', max_length=16)),
                ('result_desc', models.CharField(blank=True, default='', max_length=255)),
                ('simulated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('raw_result', models.TextField(blank=True, default='')),
                ('company_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_b2b_transfers', to='accounts.companyexpenseaccount')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_b2b_transfers_created', to=settings.AUTH_USER_MODEL)),
                ('expense_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_b2b_transfers', to='accounts.companyexpensepayment')),
            ],
            options={
                'verbose_name': 'M-Pesa B2B transfer',
                'verbose_name_plural': 'M-Pesa B2B transfers',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
