# Generated by Django 5.0.14 on 2026-09-17 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0128_general_accounts_b2b_and_float'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycashexpenserequest',
            name='mpesa_transfer',
            field=models.ForeignKey(blank=True, help_text='Outbound M-Pesa transfer created when a money request is approved.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='petty_cash_requests', to='accounts.mpesab2btransfer'),
        ),
        migrations.AddField(
            model_name='pettycashexpenserequest',
            name='payout_account_reference',
            field=models.CharField(blank=True, default='', help_text='Account reference for Paybill destinations.', max_length=32),
        ),
        migrations.AddField(
            model_name='pettycashexpenserequest',
            name='payout_destination_type',
            field=models.CharField(blank=True, choices=[('paybill', 'Paybill'), ('till', 'Buy Goods Till'), ('phone', 'Phone number')], default='', help_text='Paybill, Till, or phone when requesting money.', max_length=16),
        ),
        migrations.AddField(
            model_name='pettycashexpenserequest',
            name='payout_party_b',
            field=models.CharField(blank=True, default='', help_text='Destination Paybill, Till, or MSISDN.', max_length=20),
        ),
        migrations.AddField(
            model_name='pettycashexpenserequest',
            name='request_money',
            field=models.BooleanField(default=False, help_text='When true, finance should send money to the payout destination.'),
        ),
    ]
