# Generated by Django 5.0.14 on 2026-09-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0129_petty_cash_money_request_payout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="casetask",
            name="due_date",
            field=models.DateField(
                blank=True,
                help_text="Optional deadline for this task.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="mattertask",
            name="due_date",
            field=models.DateField(
                blank=True,
                help_text="Optional deadline for this task.",
                null=True,
            ),
        ),
    ]
