# Generated by Django 5.0.14 on 2026-09-28 10:14

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0130_casetask_mattertask_due_date_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmcompanyinformation',
            name='logo',
            field=models.ImageField(blank=True, help_text='Firm logo for letterhead, invoices, and brand mark.', null=True, upload_to=accounts.models.company_logo_upload_to),
        ),
    ]
